<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN"
    "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<!-- TMPL_IF NAME="bidi" -->
<html lang="<!-- TMPL_VAR NAME="lang" -->" xml:lang="<!-- TMPL_VAR NAME="lang" -->" dir="<!-- TMPL_VAR NAME="bidi" -->" xmlns="http://www.w3.org/1999/xhtml">
<!-- TMPL_ELSE -->
<html lang="<!-- TMPL_VAR NAME="lang" -->" xml:lang="<!-- TMPL_VAR NAME="lang" -->" xmlns="http://www.w3.org/1999/xhtml">
<!-- /TMPL_IF -->
<head>
<title>
